---
staticips: true
helper:
  name: "helper"
  ipaddr: "10.137.20.34"
dns:
  domain: "example.com"
  clusterid: "ocp4"
  forwarder1: "10.100.55.80"
  forwarder2: "10.100.55.81"
bootstrap:
  name: "bootstrap"
  ipaddr: "10.137.20.36"
masters:
  - name: "master0"
    ipaddr: "10.95.121.10"
  - name: "master1"
    ipaddr: "10.95.121.11"
  - name: "master2"
    ipaddr: "10.95.121.12"
workers:
  - name: "worker0"
    ipaddr: "10.95.121.13"
  - name: "worker1"
    ipaddr: "10.95.121.14"
  - name: "worker2"
    ipaddr: "10.95.121.15"
